Repository machine-learning-exchange/mlx, pull requests merged in 2021-12, with the labels that each got.

#272 platform specification for ARM/M1 compatability with mysql
  quickstart/docker-compose.yaml
Labels: lgtm, approved, RCOS

#266 Add docs for KIND deployment
  docs/install-mlx-on-kind.md
Labels: lgtm, approved

#281 Simplify Quickstart
  quickstart/catalog_upload.json
  quickstart/docker-compose.yaml
  quickstart/init_catalog.sh
  quickstart/init_db.sql
  tools/python/regenerate_catalog_upload_json.py
Labels: lgtm, approved

#275 Removed Dashboard Dependency on Catalog Service
  api/README.md
  quickstart/docker-compose.yaml
Labels: lgtm, approved, RCOS

#283 Link KIND Deployment Option on Main README
  README.md
  api/README.md
  docs/import-assets.md
  docs/install-mlx-on-kind.md
  docs/usage-steps.md
  tools/python/verify_doc_links.py
Labels: documentation, lgtm, approved

#282 Simplify Quickstart (2)
  api/README.md
  quickstart/README.md
Labels: documentation, lgtm, approved, API

#284 Upload MLX Workshop Doc
  docs/images/workshop/Datasets-featured-page.png
  docs/images/workshop/Datasets-launch.png
  docs/images/workshop/Datasets-output-PVC-name.png
  docs/images/workshop/Datasets-related-assets.png
  docs/images/workshop/Datasets-run-graph.png
  docs/images/workshop/Models-Swagger-UI.png
  docs/images/workshop/Models-featured-page.png
  docs/images/workshop/Models-launch.png
  docs/images/workshop/Models-predict-open-source-file.png
  docs/images/workshop/Models-run-output.png
  docs/images/workshop/Notebooks-featured-page.png
  docs/images/workshop/Notebooks-language-classification-test.png
  docs/images/workshop/Notebooks-launch.png
  docs/images/workshop/Notebooks-run-graph.png
  docs/images/workshop/Notebooks-run-logs.png
  docs/mlx-workshop.md
Labels: lgtm, approved

#285 Disable run in Quickstart (again)
  quickstart/README.md
  quickstart/docker-compose.yaml
Labels: lgtm, approved

#233 Npm update packages
  Makefile
  dashboard/origin-mlx/package-lock.json
  tools/python/verify_npm_packages.py
Labels: UI, RCOS, CI/CD

#267 Added buttons that can delete assets
  dashboard/origin-mlx/src/pages/MetaAllPage.tsx
  dashboard/origin-mlx/src/styles/Models.css
Labels: lgtm, approved, RCOS
