Repository machine-learning-exchange/mlx, pull requests merged in 2021-09, with the labels that each got.

#195 Remove detail tab and update formatting
  dashboard/origin-mlx/package.json
  dashboard/origin-mlx/src/components/Detail/DatasetDetail.tsx
  dashboard/origin-mlx/src/styles/Models.css
Labels: lgtm, approved, do-not-merge/hold

#196 Enlarge markdown viewer padding
  dashboard/origin-mlx/src/styles/Models.css
Labels: lgtm, approved, UI

#177 Adding CodeNet Dataset
  quickstart/catalog_upload.json
Labels: lgtm, approved

#203 [API] Update Python dependencies
  api/server/Dockerfile
  api/server/requirements.txt
Labels: dependencies, lgtm, approved, API

#204 Update the `pip`-install code blocks in API docs
  api/README.md
  api/server/README.md
  api/server/requirements.txt
Labels: approved

#205 [API] Don't cache KFServices
  api/codegen.sh
  api/server/swagger_server/__init__.py
  api/server/swagger_server/__main__.py
  api/server/swagger_server/swagger/swagger.yaml
  api/server/swagger_server/util.py
Labels: approved

#219 WSL troubleshooting - init_catalog.sh file not found
  quickstart/README.md
Labels: lgtm, approved

#200 Add script to regenerate `catalog_upload.json` files
  bootstrapper/catalog_upload.json
  hack/regenerate_catalog_upload_json.py
  quickstart/catalog_upload.json
Labels: lgtm, approved

#224 Remove "MAX" prefix from model names
  bootstrapper/catalog_upload.json
  quickstart/catalog_upload.json
Labels: lgtm, approved

#225 Remove extra description tab for models
  dashboard/origin-mlx/src/components/Detail/ModelDetail.tsx
Labels: lgtm, approved

#230 UI development with Docker Compose
  dashboard/origin-mlx/README.md
Labels: lgtm, approved
