Repository machine-learning-exchange/mlx, pull requests merged in 2021-07, with the labels that each got.

#124 add project references
  README.md
Labels: approved, lgtm

#125 Removing CodeNet
  quickstart/catalog_upload.json
Labels: approved, lgtm

#119 Add LFAI logo to sidebar
  dashboard/origin-mlx/src/App.tsx
  dashboard/origin-mlx/src/components/Link.tsx
  dashboard/origin-mlx/src/components/PageFooter.tsx
  dashboard/origin-mlx/src/components/Sidebar/SideBarHeader.tsx
  dashboard/origin-mlx/src/components/Sidebar/SidebarList.tsx
  dashboard/origin-mlx/src/images/landing-page.png
  dashboard/origin-mlx/src/images/lfaidata.png
  dashboard/origin-mlx/src/images/mlx-logo-name-white.png
  dashboard/origin-mlx/src/pages/ExternalLinksPage.tsx
  dashboard/origin-mlx/src/pages/LandingPage.tsx
  dashboard/origin-mlx/src/pages/MetaAllPage.tsx
  dashboard/origin-mlx/src/pages/MetaDetailPage.tsx
  dashboard/origin-mlx/src/pages/MetaFeaturedPage/MetaFeatured.tsx
  dashboard/origin-mlx/src/pages/UploadPage.tsx
  dashboard/origin-mlx/src/styles/Models.css
  dashboard/origin-mlx/src/styles/Sidebar.css
Labels: approved, lgtm

#127 Add upload_from_url support
  dashboard/origin-mlx/src/lib/api/upload.ts
  dashboard/origin-mlx/src/pages/UploadPage.tsx
  dashboard/origin-mlx/src/styles/Models.css
Labels: approved, lgtm

#135 Disable Inference Services by default in read-only deployments
  api/server/application_settings.yaml
Labels: approved, lgtm

#136 Enable anonymous read-only access for model YAMLs in Minio
  api/server/swagger_server/controllers_impl/model_service_controller_impl.py
Labels: approved, lgtm

#130 (ui) Add caching for api requests
  dashboard/origin-mlx/README.md
  dashboard/origin-mlx/src/App.tsx
  dashboard/origin-mlx/src/components/DataListItem.tsx
  dashboard/origin-mlx/src/components/Detail/DatasetDetail.tsx
  dashboard/origin-mlx/src/components/Sidebar/SidebarList.tsx
  dashboard/origin-mlx/src/components/Sidebar/SidebarListItem.tsx
  dashboard/origin-mlx/src/lib/api/artifacts.ts
  dashboard/origin-mlx/src/pages/MetaDetailPage.tsx
  dashboard/origin-mlx/src/pages/SettingsPage.tsx
  dashboard/origin-mlx/src/styles/Sidebar.css
Labels: approved, lgtm

#134 Expose Minio console in quickstart with Docker Compose
  quickstart/docker-compose.yaml
Labels: approved, lgtm

#142 move usage and troubleshooting steps
  README.md
  docs/troubleshooting.md
  docs/usage-steps.md
Labels: approved, lgtm

#138 [Quickstart] miniosetup depend on healthy minio service
  quickstart/docker-compose.yaml
Labels: approved, lgtm

#140 [API] Add caching for GET requests
  api/codegen.sh
  api/server/swagger_server/controllers_impl/component_service_controller_impl.py
  api/server/swagger_server/controllers_impl/dataset_service_controller_impl.py
  api/server/swagger_server/controllers_impl/model_service_controller_impl.py
  api/server/swagger_server/controllers_impl/notebook_service_controller_impl.py
  api/server/swagger_server/controllers_impl/pipeline_service_controller_impl.py
  api/server/swagger_server/data_access/minio_client.py
  api/server/swagger_server/util.py
Labels: approved, lgtm

#148 Fix file button and remove connections setting
  dashboard/origin-mlx/src/components/DataListItem.tsx
  dashboard/origin-mlx/src/components/Sidebar/SidebarList.tsx
  dashboard/origin-mlx/src/pages/SettingsPage.tsx
  dashboard/origin-mlx/src/styles/Models.css
  dashboard/origin-mlx/src/styles/Sidebar.css
Labels: approved, lgtm

#149 Move kfp-context to multi-user only
  manifests/base/mlx-deployments/mlx-api.yaml
  manifests/istio-auth/kustomization.yaml
  manifests/istio-auth/mlx-api-auth.yaml
  manifests/istio-auth/mlx-api-patch.yaml
Labels: approved, lgtm

#151 [API] Add missing parameters to NotebookOp
  api/server/swagger_server/code_templates/run_notebook.TEMPLATE.py
  api/server/swagger_server/code_templates/run_notebook_with_dataset.TEMPLATE.py
  api/server/swagger_server/gateways/kubeflow_pipeline_service.py
Labels: approved

#141 [API] Use waitress as production WSGI server for MLX API
  api/server/requirements.txt
  api/server/swagger_server/__main__.py
Labels: approved

#146 Update MLX single user deployment page
  docs/mlx-read-only-deployment.md
  docs/mlx-setup.md
Labels: approved, documentation, lgtm

#158 [API] Extract pipeline description from YAML
  api/server/swagger_server/controllers_impl/pipeline_service_controller_impl.py
Labels: approved, lgtm

#154 update single/multi-user deployment instructions
  docs/install-mlx-on-kubeflow.md
  docs/mlx-setup.md
Labels: approved, lgtm

#153 Add v1beta kfservices support
  dashboard/origin-mlx/src/components/Detail/KFServingDetail.tsx
  dashboard/origin-mlx/src/lib/api/upload.ts
  dashboard/origin-mlx/src/pages/KFServingAllPage.tsx
  dashboard/origin-mlx/src/pages/KFServingDetailPage.tsx
  dashboard/origin-mlx/src/pages/KFServingFeaturedPage/KFServingFeatured.tsx
  dashboard/origin-mlx/src/pages/KFServingFeaturedPage/KFServingFeaturedPage.tsx
  dashboard/origin-mlx/src/pages/KFServingUploadPage.tsx
  dashboard/origin-mlx/src/pages/LandingPage.tsx
  dashboard/origin-mlx/src/pages/MetaAllPage.tsx
  dashboard/origin-mlx/src/pages/MetaDetailPage.tsx
  dashboard/origin-mlx/src/pages/MetaFeaturedPage/MetaFeaturedPage.tsx
  dashboard/origin-mlx/src/pages/UploadPage.tsx
Labels: approved, lgtm

#164 Update MLX with Kubeflow manifests prerequisites to install kustomize 3.2.0
  docs/mlx-setup.md
Labels: approved, lgtm

#165 Fix express routing of static file
  dashboard/origin-mlx/server/server.ts
  dashboard/origin-mlx/src/App.tsx
  dashboard/origin-mlx/src/pages/Default404Page.tsx
  dashboard/origin-mlx/src/pages/MetaDetailPage.tsx
  dashboard/origin-mlx/src/styles/Models.css
Labels: approved, lgtm

#169 Add search bar
  dashboard/origin-mlx/package-lock.json
  dashboard/origin-mlx/package.json
  dashboard/origin-mlx/src/pages/MetaDetailPage.tsx
  dashboard/origin-mlx/src/pages/MetaFeaturedPage/MetaFeatured.tsx
  dashboard/origin-mlx/src/pages/MetaFeaturedPage/MetaFeaturedPage.tsx
  dashboard/origin-mlx/src/styles/Models.css
  dashboard/origin-mlx/src/styles/Sidebar.css
Labels: approved, lgtm
