Repository machine-learning-exchange/mlx, pull requests merged in 2021-08, with the labels that each got.

#175 Fix quickstart startup sequence
  api/examples/pipelines_api.py
  api/server/Dockerfile
  quickstart/README.md
  quickstart/docker-compose.yaml
Labels: approved, lgtm, size/S

#174 Add GitHub actions to build UI and API images
  .github/workflows/mlx-ci.yml
Labels: approved, lgtm

#179 Add max/dax description in details page
  dashboard/origin-mlx/src/components/Detail/DatasetDetail.tsx
  dashboard/origin-mlx/src/components/Detail/ModelDetail.tsx
  dashboard/origin-mlx/src/components/MarkdownViewer.tsx
  dashboard/origin-mlx/src/styles/Models.css
Labels: enhancement, approved

#178 Add troubleshooting steps to Quickstart README
  quickstart/README.md
Labels: documentation, approved
