Repository machine-learning-exchange/mlx, pull requests merged in 2021-05, with the labels that each got.

#60 Add OWNERS file
  OWNERS
Labels: lgtm

#61 Update .travis.yml to always push images for nightly builds
  .travis.yml
Labels: approved, lgtm, size/S

#62 Update readme details for Kubeflow 1.3
  README.md
Labels: approved, lgtm, size/XS

#63 Add link to catalog demo on main README
  README.md
Labels: approved, size/S

#64 restructure deployment options
  README.md
Labels: approved, size/S

#51 Update MLX manifests to work with kubeflow 1.3
  docs/install-mlx-on-kubeflow.md
  manifests/base/mlx-api.yaml
  manifests/istio-auth/kustomization.yaml
  manifests/istio-auth/ml-pipeline-api-auth.yaml
  manifests/istio-auth/mlx-api-auth.yaml
  manifests/istio-auth/mlx-ui-auth.yaml
  manifests/istio-auth/mysql-auth.yaml
  manifests/multi-user/mlx-api-auth.yaml
Labels: approved, lgtm, size/L

#67 remove operator install docs and add kfctl install docs
  README.md
  docs/mlx-install-with-kubeflow.md
Labels: approved, lgtm

#69 Update logo and change deployment brand
  dashboard/origin-mlx/src/components/Sidebar/SideBarHeader.tsx
  dashboard/origin-mlx/src/images/mlx-logo-white.png
  dashboard/origin-mlx/src/styles/Sidebar.css
  manifests/base/mlx-ui.yaml
Labels: approved, lgtm
