Repository machine-learning-exchange/mlx, pull requests merged in 2021-06, with the labels that each got.

#68 [mlx-ui] Add secret for login
  manifests/base/mlx-ui.yaml
Labels: approved, lgtm

#71 Remove swagger-codegen-cli jar file
  api/README.md
  api/codegen.sh
Labels: approved, lgtm

#75 fix manifests and change mlx subpath
  manifests/base/mlx-api.yaml
  manifests/base/mlx-ui.yaml
  manifests/istio-auth/kustomization.yaml
  manifests/istio-auth/mlx-ext-authz.yaml
Labels: approved, lgtm

#59 Update API to kfp==1.5.0, kfp-tekton==0.8.0, add `namespace` to pipeline API
  api/client/README.md
  api/client/docs/ApiPipeline.md
  api/client/docs/ApiPipelineExtended.md
  api/client/docs/ComponentServiceApi.md
  api/client/docs/ModelServiceApi.md
  api/client/docs/NotebookServiceApi.md
  api/client/swagger_client/models/api_pipeline.py
  api/client/swagger_client/models/api_pipeline_extended.py
  api/generate_code.sh
  api/server/mlx-api.yml
  api/server/requirements.txt
  api/server/setup.py
  api/server/swagger_server/__init__.py
  api/server/swagger_server/__main__.py
  api/server/swagger_server/controllers_impl/pipeline_service_controller_impl.py
  api/server/swagger_server/data_access/mysql_client.py
  api/server/swagger_server/models/api_pipeline.py
  api/server/swagger_server/models/api_pipeline_extended.py
  api/server/swagger_server/swagger/swagger.yaml
  api/swagger/swagger.yaml
  quickstart/docker-compose.yaml
  quickstart/init_db.sql
Labels: approved, lgtm, size/L

#53 Check permission for all proxy requests to mlx-api
  dashboard/origin-mlx/server/server.ts
Labels: approved, lgtm

#81 Update wording and fix initial artifact setting
  dashboard/origin-mlx/src/lib/stores/artifacts.ts
  dashboard/origin-mlx/src/pages/UploadPage.tsx
Labels: approved, lgtm

#82 Update logo in docs and UI tab icon
  dashboard/origin-mlx/public/favicon-codait.ico
  dashboard/origin-mlx/public/favicon.ico
  dashboard/origin-mlx/public/index.html
  dashboard/origin-mlx/public/manifest.json
  dashboard/origin-mlx/public/mlx-logo-white.png
  docs/images/CatalogImport.png
  docs/images/mlx.png
Labels: approved, lgtm

#86 Quickstart should use nightly images for API and UI
  quickstart/docker-compose.yaml
Labels: approved, lgtm

#84 Cleanup react routing and update upload page wording
  dashboard/origin-mlx/src/App.tsx
  dashboard/origin-mlx/src/pages/KFServingUploadPage.tsx
  dashboard/origin-mlx/src/pages/UploadPage.tsx
Labels: approved, lgtm

#87 [mlx-ui] Add an ENV var to disable login
  dashboard/origin-mlx/README.md
  dashboard/origin-mlx/package.json
  dashboard/origin-mlx/server/server.ts
  dashboard/origin-mlx/server/users.ts
  dashboard/origin-mlx/src/lib/util.ts
  manifests/base/mlx-ui.yaml
Labels: approved, lgtm

#90 Revert "Cleanup react routing and update upload page wording"
  dashboard/origin-mlx/src/App.tsx
  dashboard/origin-mlx/src/pages/KFServingUploadPage.tsx
  dashboard/origin-mlx/src/pages/UploadPage.tsx
Labels: approved

#99 Run quickstart as admin
  quickstart/docker-compose.yaml
Labels: approved, lgtm

#103 Move prereqs to deployment instructions
  README.md
  docs/mlx-install-with-kubeflow.md
  quickstart/README.md
Labels: approved, lgtm

#98 [API] Use `ml-pipeline` service instead of `ml-pipeline-ui`
  api/examples/pipelines_api.py
  api/server/swagger_server/gateways/kubeflow_pipeline_service.py
  quickstart/docker-compose.yaml
Labels: approved, lgtm

#104 Add yaml and yml support and fix hard fail on invalid component
  dashboard/origin-mlx/src/components/Detail/ComponentDetail.tsx
  dashboard/origin-mlx/src/lib/api/upload.ts
  dashboard/origin-mlx/src/pages/UploadPage.tsx
Labels: approved, lgtm

#106 [mlx-ui] fix: empty REACT_APP_BASE_PATH env
  dashboard/origin-mlx/server/server.ts
Labels: approved, lgtm

#105 [mlx-ui] Add kubeflow-userid header
  dashboard/origin-mlx/server/server.ts
Labels: approved, lgtm

#110 [mlx-ui] Use proper namespace in iframe
  dashboard/origin-mlx/src/App.tsx
Labels: approved, lgtm

#109 Add additional katalog pipelines to catalog_upload.json
  bootstrapper/catalog_upload.json
Labels: approved, lgtm

#92 Add MLX minimum setup
  docs/mlx-setup.md
Labels: approved, lgtm

#112 Fix model config image for MLX
  api/server/swagger_server/code_templates/serve_kubernetes.TEMPLATE.py
Labels: approved, lgtm

#96 Add title case and remove dashes from UI assests
  dashboard/origin-mlx/src/lib/util.ts
  dashboard/origin-mlx/src/pages/KFServingDetailPage.tsx
  dashboard/origin-mlx/src/pages/KFServingUploadPage.tsx
  dashboard/origin-mlx/src/pages/MetaAllPage.tsx
  dashboard/origin-mlx/src/pages/MetaDetailPage.tsx
  dashboard/origin-mlx/src/pages/MetaFeaturedPage/MetaCard.tsx
  dashboard/origin-mlx/src/pages/UploadPage.tsx
Labels: approved, lgtm

#114 [mlx-api] prepare context.json for kfp.KfpClient
  manifests/base/mlx-api.yaml
Labels: approved, lgtm

#113 Add admin route, cleanup react routing, and add redirect
  dashboard/origin-mlx/src/App.tsx
  dashboard/origin-mlx/src/pages/KFServingUploadPage.tsx
Labels: approved, lgtm

#107 Fix status line bug and improve form feedback
  dashboard/origin-mlx/src/pages/KFServingUploadPage.tsx
  dashboard/origin-mlx/src/pages/UploadPage.tsx
  dashboard/origin-mlx/src/styles/Models.css
Labels: approved, lgtm

#117 [mlx-ui] Add js lib from kubeflow dashboard
  dashboard/origin-mlx/public/dashboard_lib.bundle.js
  dashboard/origin-mlx/public/dashboard_lib.bundle.js.map
Labels: approved, lgtm

#118 Add manifest to setup MLX prod multi-user
  dashboard/origin-mlx/package-lock.json
  dashboard/origin-mlx/package.json
  docs/install-mlx-on-kubeflow.md
  manifests/prod-multi-user/envoy-filter-patch.yaml
  manifests/prod-multi-user/kubeflow-dashboard-patch.yaml
  manifests/prod-multi-user/kustomization.yaml
  manifests/prod-multi-user/mlx-ext-authz-patch.yaml
  manifests/prod-multi-user/mlx-ui-patch.yaml
  manifests/prod-multi-user/oidc-patch.yaml
Labels: approved, lgtm

#120 Add Slack and Mailing Lists
  README.md
Labels: approved, documentation, lgtm

#121 [API] Use swagger-codegen-cli version 2.4.8
  .gitignore
  api/README.md
  api/client/.swagger-codegen/VERSION
  api/codegen.sh
  api/server/.swagger-codegen/VERSION
Labels: approved, lgtm
