Repository machine-learning-exchange/mlx, pull requests merged in 2022-03, with the labels that each got.

#309 Update kustomization.yaml to v0.2.0 version
  manifests/base/mlx-deployments/kustomization.yaml
Labels: lgtm, approved

#320 Do not verify links in project dependencies
  tools/python/verify_doc_links.py
Labels: lgtm, approved, test

#314 Add navigation and description table of docs
  docs/README.md
Labels: documentation, lgtm, approved, do-not-merge/work-in-progress

#317 Script to update the docs table
  Makefile
  docs/README.md
  docs/mlx-read-only-deployment.md
  tools/python/update_doc_table.py
Labels: approved

#315 Modified the way sed version is set
  api/codegen.sh
  tools/bash/add_license_headers.sh
Labels: approved
