Repository machine-learning-exchange/mlx, pull requests merged in 2022-06, with the labels that each got.

#338 Fix startup errors in `mlx-ui` Docker container (prereg to run on OpenShift)
  dashboard/origin-mlx/Dockerfile
  dashboard/origin-mlx/src/components/Detail/DatasetDetail.tsx
  dashboard/origin-mlx/src/components/Detail/KFServingDetail.tsx
Labels: lgtm, approved

#339 Run mlx-ui as non-root user
  dashboard/origin-mlx/Dockerfile
  dashboard/origin-mlx/README.md
  dashboard/origin-mlx/package-lock.json
  dashboard/origin-mlx/server/package-lock.json
Labels: lgtm, approved, UI

#346 Update MLX setup instructions for KF 1.5
  docs/install-mlx-on-kind.md
  docs/mlx-setup.md
  docs/mlx-workshop.md
Labels: openshift

#342 fix selected assets show up in different menus
  dashboard/origin-mlx/src/pages/MetaAllPage.tsx
Labels: lgtm, approved, UI, Jump-Start
